language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  # create snakemake env
  #- conda create -q -n snakemake snakemake python=$TRAVIS_PYTHON_VERSION
  - conda install -y mamba
  - mamba env create -y -n dada2env --file dependencies.yml
  # add additional stuff to setup below

script:
  - source activate dada2env
  # run the workflow
  # put a test case into the subfolder .test (e.g., use https://github.com/snakemake-workflows/ngs-test-data as a submodule)
  - ./test.py
