# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

sampletable: "samples.tsv"


threads: 4

truncLen:
  - 150
  - 120
maxEE:
  - 2
  - 2
truncQ: 2
learn_nbases: 100e6
chimera_method: "consensus"
max_length_variation: 7     # how many nucleotide can a sequence be longer or shorter than the mode sequence length

idtaxa_dbs: # can be downloaded from http://www2.decipher.codes/Downloads.html
#  Silva: "/Users/silas/Desktop/Sequencing_Data/16S/TaxonmyDBs/SILVA_SSU_r132_March2018.RData"
#  GTDB: "/Users/silas/Desktop/WarmMicrobiota/TaxonmyDBs/GTDB_r86-mod_September2018.RData"
